###################################################
#
# Pipeline Triggerer Extension
# (Azure Pipelines) CI
#
###################################################

trigger:
  branches:
    include:
    - master
  paths:
      include:
      - /src/*

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  projName: pipeline-triggerer-extension
  artifactName: $(projName)-ext
  publisherId: joalmeid
  vsMarketplaceServiceConnetion: vs-marketplace
  # pat: #required

stages:
- stage: Build_Ext
  displayName: Build Extension
  jobs:
  - job: BuildJob
    displayName: Build Extension
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    - template: template-build.yaml
      parameters:
        publisherId: $(publisherId)
        projName: $(projName)
        marketplaceServiceConnection: $(vsMarketplaceServiceConnetion)
        artifactName: $(artifactName)

- stage: Publish_Ext_Dev
  displayName: DEV
  dependsOn: Build_Ext
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: PublishExtDev
    displayName: Publish Extension
    pool:
      vmImage: 'ubuntu-latest'
    environment: DEV
    strategy:
      runOnce:
        deploy: 
          steps:
          - template: template-release.yaml
            parameters:
              publisherId: $(publisherId)
              projName: $(projName)
              marketplaceServiceConnection: $(vsMarketplaceServiceConnetion)
              artifactName: $(artifactName)
              extensionName: 'Pipeline Triggerer (dev)'
              extensionVisibility: private
              extensionTag: -dev

- stage: Publish_Ext_Prod
  displayName: PROD
  dependsOn: Publish_Ext_Dev
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: PublishExtDev
    displayName: Publish Extension
    pool:
      vmImage: 'ubuntu-latest'
    environment: PROD
    strategy:
      runOnce:
        deploy: 
          steps:
          - template: template-release.yaml
            parameters:
              publisherId: $(publisherId)
              projName: $(projName)
              marketplaceServiceConnection: $(vsMarketplaceServiceConnetion)
              artifactName: $(artifactName)
              extensionVisibility: public
